apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observers-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/observers/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observers-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/ingress-nginx/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/cloudflared/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: security/vault
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: security/vso
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vso
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: blog-dev
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/ghost/overlays/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

