apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog-dev
  namespace: argocd
spec:
  description: Blogstack dev project boundaries
  sourceRepos:
    - https://github.com/your-org/blogstack-k8s
  destinations:
    - namespace: blog-dev
      server: https://kubernetes.default.svc
    - namespace: observers-dev
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx-dev
      server: https://kubernetes.default.svc
    - namespace: cloudflared-dev
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: vso
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

