apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: apps/observers/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observers
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: apps/ingress-nginx/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: apps/cloudflared/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: security/vault
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: security/vso
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vso
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: blog
  source:
    repoURL: https://github.com/your-org/blogstack-k8s
    path: apps/ghost/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

