# BlogStack Applications
# Deployment order controlled by sync-wave annotations
#
# Architecture:
# - observers: Prometheus/Grafana/Loki stack (installs CRDs)
# - observers-probes: Blackbox Exporter probes (uses Probe CRD)
# - ingress-nginx: Ingress controller (uses ServiceMonitor CRD)
# - cloudflared: Cloudflare Tunnel for ingress
# - vault: HashiCorp Vault for secrets
# - vso-operator: Vault Secrets Operator (installs CRDs)
# - vso-resources: Vault connection and secret mappings (uses VSO CRDs)
# - ghost: Ghost CMS + MySQL (uses VaultStaticSecret CRD)

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/observers/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observers-probes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/observers-probes/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: observers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/ingress-nginx/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/cloudflared/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: security/vault
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: security/vso-operator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: security/vso-resources
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: blog
  source:
    repoURL: https://github.com/gigio1023/blogstack-k8s
    path: apps/ghost/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
