apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: vso
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: blog
    serviceAccount: default
    audiences:
      - https://kubernetes.default.svc
  vaultConnectionRef: vault-conn
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-conn
  namespace: vso
spec:
  address: http://vault.vault.svc:8200

