apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backup-s3
  namespace: blog
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: blog/prod/backup
  destination:
    name: backup-s3
    create: true
  refreshAfter: 24h

