apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: blog
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
