apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: timezone
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.15.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
          args:
            - |
              export DATA_SOURCE_NAME="${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}@(localhost:3306)/"
              exec /bin/mysqld_exporter
          ports:
            - name: metrics
              containerPort: 9104
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          env:
            - name: MYSQL_EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: user
            - name: MYSQL_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
