name: Deploy Ghost Theme

on:
  push:
    paths:
      - 'theme/**'

jobs:
  deploy:
    runs-on: blogstack-k8s-arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: custom

