apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: prod-config
    envs:
      - ../../../../config/dev.env

replacements:
  - source:
      kind: ConfigMap
      name: prod-config
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          name: ghost
        fieldPaths:
          - spec.rules.0.host

